### ISSUE TITLE
TODO: Management: Categories

### ISSUE THREAD

**Issue by VA2XJM** [xJMV/PrepInventory#3]
- [x] Make DB tables.
- [x] Make managements_categories.php (Categories listing)
- [x] Make managements_categories_add.php (Categories action)
- [x] Make managements_categories_edit.php (Categories action)
- [x] Make managements_categories_delete.php (Categories action)

**Comment by VA2XJM** [comment]
Commited to branch V0.1.0a
