### ISSUE TITLE
TODO: Management: Units

### ISSUE THREAD

**Issue by VA2XJM** [xJMV/PrepInventory#4]
- [x] Make DB tables.
- [x] Make managements_units.php (Units listing)
- [x] Make managements_units_add.php (Units action)
- [x] Make managements_units_edit.php (Units action)
- [x] Make managements_units_delete.php (Units action)

---
- Allow edition but list all items listed with that measurement unit so admin can ensure that there will be no break up.
- Allow unit to be deleted only if no item is attached to this unit. List all attached items with edition link so admin can make proper changes prior to delete.

**Comment by VA2XJM** [comment]
All done for now.
