### ISSUE TITLE
TODO: Management: Items

### ISSUE THREAD

**Issue by VA2XJM** [xJMV/PrepInventory#5]
- [x] Make DB tables.
- [x] Make managements_items.php (Items listing)
- [x] Make managements_items_add.php (Items action)
- [x] Make managements_items_edit.php (Items action)
- [x] Make managements_items_delete.php (Items action)

---
- Allow edition but list all inventory listed with that item so admin can ensure that there will be no break up.
- Allow item to be deleted only if no inventory is attached to this item. List all attached inventory with edition link so admin can make proper changes prior to delete.

**Comment by VA2XJM** [comment]
Done
