### ISSUE TITLE
TODO: Inventory

### ISSUE THREAD

**Issue by VA2XJM** [xJMV/PrepInventory#6]
- [x] Make DB table.
- [x] Make inventory.php (Inventory navigation)
- [x] Make inventory_details.php (View item details)
- [x] Make inventory_add.php (Add a line to the inventory)
- [x] Make inventory_edit.php (Edit an inventory line)
- [x] Make inventory_delete.php (Delete an inventory line)
- [x] Make inventory_shopping.php (Display all inventory not filled to 100%)

**Comment by VA2XJM** [comment]
Everything works.
