### ISSUE TITLE
TODO: Users management

### ISSUE THREAD

**Issue by VA2XJM** [xJMV/PrepInventory#7]
- [ ] Make DB tables.
- [ ] Make a user management area so admin can manage users via database instead of config file.
- [ ] Make settings.php so users can manage their accounts and change their password.

**Comment by VA2XJM** [comment]
Use 2 types of users: admin and user
Make a token auth mod for devices (inventory only)

**Comment by VA2XJM** [comment]
drop it for now... it requires lots of works for not much since the typical setup will requires few users only...
